import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "~/utils/fonts";
import { cn } from "~/utils/helpers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppins.variable, `antialiased`)}>{children}</body>
    </html>
  );
}
